services:
  web:
     build:
      context: ./codyssey
      dockerfile: Dockerfile
      image: codyssey-nginx:compose
      container_name: compose-web
      ports:
        - "${HOST_PORT:-8090}:80"
      environment:
        - APP_MODE=${APP_MODE:-dev}
      volumes:
        - ./codyssey/app:/usr/share/nginx/html:ro

  checker:
    image: alpine:3.20
    container_name: compose-checker
    depends_on:
      - web
    command: sh -c "sleep 2; wget -qO- http://web:80; sleep 60"
